Working pagination
bartosz-kasprzyk/movies-browser pull request #16
Opened 2024-03-10 00:42 UTC by doncochino

Please check and let me know.

2024-03-15 15:38 UTC, bartek-kasprzyk requested changes

2024-03-15 15:38 UTC, bartek-kasprzyk commented on src/common/Pagination/index.js
Pagination works great, but I found one issue.
When you're for example on page 8 and you click on a movie/person to see the details and then you click the left arrow on your browser to go back to the list, the url says
`?page=8`
as it should, but the pagination goes back to
`Page 1 of 500`

2024-03-15 21:16 UTC, VITALIKXXX approved these changes

2024-03-16 12:31 UTC, doncochino commented on src/common/Pagination/index.js
Already done.

2024-03-17 17:24 UTC, bartek-kasprzyk approved these changes
Great, now the pagination works perfectly!
The only thing I would've added is a loading state between different pages. It would be great to see the Loading component for half a second and then the next results, but that's a small thing you can change if you have the time to do so. Anyway - good job!

2024-03-17 17:37 UTC, bartek-kasprzyk commented
I've approved the changes, but didn't check the console. Are you getting the same error as I do, or is it only on my end? It looks like this:

![error](https://github.com/bartek-kasprzyk/movies-browser/assets/143531298/3703d503-4f7e-4df3-ae8b-819ecb6b813b)

2024-03-17 18:08 UTC, doncochino commented
> I've approved the changes, but didn't check the console. Are you getting the same error as I do, or is it only on my end? It looks like this:
> 
> ![error](https://private-user-images.githubusercontent.com/143531298/313493256-3703d503-4f7e-4df3-ae8b-819ecb6b813b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTg0OTYsIm5iZiI6MTcxMDY5ODE5NiwicGF0aCI6Ii8xNDM1MzEyOTgvMzEzNDkzMjU2LTM3MDNkNTAzLTRmN2UtNGRmMy1hZThiLTgxOWVjYjZiODEzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxNzU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzIwNTNiNDY0ODkzYTU2ZWM2NjRiNzUxMzlhZmZlNTA2ZWQ5MGFjM2RkM2RjZjM1NGU0YzNkNjlhMjYzMTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qYTeLYHhv2CAspStl0-N0TMwMwtLPsfaC9fN2u-IzPg)

This is also the case for me, but it is the result of checking pages above 500 that do not return results.

2024-03-17 19:40 UTC, merged