Search results2
bartosz-kasprzyk/movies-browser pull request #17
Opened 2024-03-10 05:49 UTC by VITALIKXXX

2024-03-15 15:22 UTC, bartek-kasprzyk requested changes

2024-03-15 15:22 UTC, bartek-kasprzyk commented on src/common/Header/SearchBar/index.js
On "working-searchbar" branch there already is a SearchBar component with necessary hooks

2024-03-15 15:22 UTC, bartek-kasprzyk commented on src/common/searchResults/index.js
> +    }, [query]);
Downloading API data with debounce is in separate file useSearchResults.js

2024-03-15 15:22 UTC, bartek-kasprzyk commented on src/common/searchResults/index.js
> +        </Container>
There should be two different outcomes depending on what the person was searching for (movies/people)

2024-03-16 20:06 UTC, doncochino approved these changes

2024-03-18 03:58 UTC, doncochino commented on src/common/Header/SearchBar/index.js
Maybe because "Search Results 2" was created before "working search bar".

2024-03-24 00:00 UTC, closed without merging