Feature/person list
bartosz-kasprzyk/movies-browser pull request #9
Opened 2024-02-17 20:07 UTC by bartek-kasprzyk

Póki co jeszcze bez pobranych danych z api, ale proszę o sprawdzenie 😊

2024-02-17 22:08 UTC, doncochino commented
Super responsywność. Niepotrzebny `subtitle` przez co kafelki się wydłużają (pierwszy rząd).

2024-02-18 13:40 UTC, bartek-kasprzyk commented
> Super responsywność. Niepotrzebny `subtitle` przez co kafelki się wydłużają (pierwszy rząd).

A no tak, subtitle w PersonList się nie przyda, ale chciałem już zrobić uniwersalny kafelek. 😋 Dzięki!

2024-02-23 20:18 UTC, doncochino requested changes

2024-02-23 20:18 UTC, przemyslaw-pacek commented on src/common/Tile/styled.js
> +    border-radius: 5px;
Better to add here:
    width: 176px;
    height: 231px;
    object-fit: cover;
Because a photo downloaded from API may have different dimensions and, most importantly, different proportions and will not be displayed correctly, while object-fit will adjust to the given resolution.

2024-02-23 20:18 UTC, przemyslaw-pacek commented on src/common/Tile/styled.js
> +`;
Can be added to Description (text-align: center;) and removed from StyledTitle and StyledSubtitle. It would be best if removed Description and (text-align: center;) added to Wrapper.

2024-02-23 20:18 UTC, przemyslaw-pacek commented on src/common/Tile/styled.js
> +    margin: 16px;
Here I would replace the margin with padding, since the margin cuts off the top and bottom of the link in Tile.
![Zrzut ekranu 2024-02-21 155439](https://github.com/bartek-kasprzyk/movies-browser/assets/137653393/25ade812-792d-46c0-a616-3cbaf35dd3d7)

2024-02-24 15:41 UTC, bartek-kasprzyk commented on src/common/Tile/styled.js
> +`;
I've moved text-align to Description 😋 Can't remove the Description component, cause it would mess up the spacing and line height

2024-02-24 15:49 UTC, bartek-kasprzyk commented
Thanks for the feedback! I've added all of these changes - pull request ready for another review 😎

2024-02-24 20:46 UTC, doncochino approved these changes

2024-02-25 20:26 UTC, VITALIKXXX approved these changes

2024-02-26 14:36 UTC, merged